version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.13
    container_name: rabbitmq
    ports:
    - "5552:5552"
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream advertised_host localhost"
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stream rabbitmq_management && rabbitmq-server"
  postgres-db:
    image: postgres:17.2
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booksyclone
