version: '3.4'

services:
  booksyclone:
    image: ${DOCKER_REGISTRY-}booksyclone
    build:
      context: .
      dockerfile: BooksyClone/Dockerfile
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream advertised_host localhost"
    volumes:
    - ./data:/var/lib/rabbitmq
    - ./logs:/var/log/rabbitmq
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stream rabbitmq_management"
  postgres-db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booksyclone
