name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Copy appsettings.json
        run: cp ./BooksyClone/appsettings.Tests.json ./BooksyClone/appsettings.json

      - name: Start containers
        run: docker compose -f "docker-compose.ci.yml" up -d

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore NuGet packages
        run: dotnet restore ./BooksyClone/BooksyClone.sln

      - name: Build
        run: dotnet build ./BooksyClone/BooksyClone.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./BooksyClone/BooksyClone.sln --configuration Release --no-build --logger:"console;verbosity=normal"

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.ci.yml" down
